spring.application.name=sql-intro

# Veritaban? Ba?lant? Bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/week5_1
spring.datasource.username=postgres
spring.datasource.password=1903

# Hibernate & JPA Ayarlar?
# 'none' yaparak Hibernate'in tablolar? silip yeniden olu?turmas?n? engelliyoruz (Verilerin silinmemesi için)
spring.jpa.hibernate.ddl-auto=none

# SQL sorgular?n? konsolda görmek istersen (Hata ay?klamak için çok faydal?d?r)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect (Sürücü uyumlulu?u için)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect